Repository lob/litmus, pull requests merged in 2018-08, with the labels that each got.

#10 feat(number-validation): Added validation functions and test cases for Number data type
  README.md
  lib/type/number.ex
  test/litmus_test.exs
  test/type/number_test.exs
Labels: Approved

#12 fix(boolean): simplifies check_booelan_values return
  lib/type/boolean.ex
Labels: Approved

#13 fix(package): Update usage example and package files
  README.md
  mix.exs
Labels: LGTM'd Once

#14 chore(spec): changes binary to String.t()
  README.md
  lib/litmus.ex
  lib/required.ex
  lib/type.ex
  lib/type/any.ex
  lib/type/boolean.ex
  lib/type/string.ex
Labels: Approved, Atlas

#15 fix(allow-nil): Convert nil value of data to empty string
  README.md
  lib/type/string.ex
  test/type/string_test.exs
Labels: Approved, LGTM'd Once

#18 chore(plug): add missing specs
  lib/litmus/plug.ex
Labels: Approved, Atlas

#19 feat(nil-handling): more consistent handling of nil + docs improvements
  README.md
  lib/litmus.ex
  lib/litmus/required.ex
  lib/litmus/type/any.ex
  lib/litmus/type/boolean.ex
  lib/litmus/type/list.ex
  lib/litmus/type/number.ex
  lib/litmus/type/string.ex
  mix.exs
  test/litmus/required_test.exs
  test/litmus/type/any_test.exs
  test/litmus/type/boolean_test.exs
  test/litmus/type/list_test.exs
  test/litmus/type/number_test.exs
  test/litmus/type/string_test.exs
  test/litmus/type_test.exs
  test/litmus_test.exs
Labels: Approved, Atlas

#20 feat(datetime): adds DateTime type
  README.md
  lib/litmus/type.ex
  lib/litmus/type/date_time.ex
  test/litmus/type/date_time_test.exs
  test/litmus_test.exs
Labels: Approved, Atlas
